### ISSUE TITLE
evaluate coulomb 0.5.0-RC1

### ISSUE THREAD

**Issue by erikerlandson** [erikerlandson/coulomb#100]
This is an issue to track smoke-testing publication of 0.5.0-RC1, which is the first release cross-published to scala.js and jvm.

**Comment by erikerlandson** [comment]
@cquiroz  can you take release candidate 0.5.0-RC1 for a spin with scala.js and jvm just to sanity check that it's working?

**Comment by cquiroz** [comment]
It is working, I updated a PR I had previously on a local snapshot. Tests are working too

https://github.com/gemini-hlsw/gsp-core/pull/125

**Comment by erikerlandson** [comment]
Nice.  I've been having friction pushing these libs to bintray. I am going to test publishing to my sonatype account to see if it's more stable.

**Comment by cquiroz** [comment]
I have been setting up sbt-ci-release on all my proyecta to simplify the release process.

**Comment by erikerlandson** [comment]
I've been thinking about that. Everyone likes it. I don't maintain a lot of projects and so far "sbt +publish" isn't sufficiently painful for me to switch :grin: 

I get increasingly frequent timeout errors and other failures publishing coulomb to bintray, which seems to be correlated with bintray's weird latency on publishing even small packages, combined with my ever-growing list of coulomb sub-projects

**Comment by erikerlandson** [comment]
I'm wading through the sonatype workflow to create the namespace for publishing. I'm going to do a test publish there for a "-RC2" and make a decision where I publish the official 0.5.0 releas

**Comment by erikerlandson** [comment]
@cquiroz  I have published 0.5.0-RC2 up on sonatype - this should not require the bintray resolver.  RC2 is identical to RC1 except for being published to sonatype instead of bintray.

**Comment by cquiroz** [comment]
Thanks RC2 is working out of maven central

**Comment by erikerlandson** [comment]
official release 0.5.0 is published :tada:  thanks @cquiroz !
