### ISSUE TITLE
mdoc:fail behaving weirdly

### ISSUE THREAD

**Issue by erikerlandson** [erikerlandson/coulomb#309]
@armanbilge   I am seeing weird behaviors for mdoc code blocks where error (`:fail`) is expected.

It is behaving as if it is keeping a previous error message instead of reporting the actual error message:

![image](https://user-images.githubusercontent.com/259898/178158550-049c6c2f-f4ef-4619-bb3f-aa981c658667.png)

That error is from previous fail demo with a deliberately bad Quantity expression, instead of the error for `7 + false`

**Comment by erikerlandson** [comment]
All the code blocks that compile correctly seem to be rendering fine.

**Comment by armanbilge** [comment]
That is really really strange 🤔 I don't think I've used the `:fail` modifier so I can't think why it might do that. If you can minimize it seems like a bug. It might even be Scala 3 specific since that's a new compiler and perhaps this part of the mdoc/Scala 3 integration hasn't been tested.

**Comment by erikerlandson** [comment]
I'll file an issue for mdoc, but here is a minimal example

````
```scala mdoc:fail
val nope = "foo" * "goo"
```

```scala mdoc:fail
val bad = "moo" * "loo"
```
````

![image](https://user-images.githubusercontent.com/259898/178159799-7e597218-b0cc-41ca-89ad-bcb6d63189e1.png)

**Comment by erikerlandson** [comment]
xref: https://github.com/scalameta/mdoc/issues/663

**Comment by erikerlandson** [comment]
https://github.com/scalameta/mdoc/pull/664 Fixes this - I am building with a snapshot to pick it up until it makes it into a release
