### ISSUE TITLE
Consider supporting Scala Native

### ISSUE THREAD

**Issue by ekrich** [erikerlandson/coulomb#314]
Now that Scala Native supports all the Scala versions and many libraries have been ported this may be possible. Scala Native also supports Window, Unix, macOS and others.

**Comment by armanbilge** [comment]
Yup, it already does :)
https://github.com/erikerlandson/coulomb/releases/tag/v0.6.0-M2

**Comment by ekrich** [comment]
When I looked in the develop branch I didn't see anything.

**Comment by erikerlandson** [comment]
@ekrich  I'm getting fairly close to making `scala3` the new main-branch, and `develop` will become legacy for scala 2.13, but not quite there yet.

**Comment by ekrich** [comment]
@erikerlandson Sorry about that, I didn't poke around enough and got thrown off. Funny thing was that I found it under native via Scaladex but didn't trust it.
