### ISSUE TITLE
2 Issues:  Simplifying and exporting time units

### ISSUE THREAD

**Issue by benhutchison** [erikerlandson/coulomb#405]
1.

```scala
case class TimeUnit(code: String, interval: Quantity[Long, coulomb.units.time.Second]):
  def intervalsPerDay: Quantity[Long, 1] = 24L.withUnit[Hour].tquot(interval)
//  def intervalsPerDay: Quantity[Long, coulomb.units.time.Hour / coulomb.units.si.Second] = 24L.withUnit[Hour].tquot(interval)
```

Surprised it doesnt compile with:
```
Found:    coulomb.Quantity[?1.VO, ?1.UO]
Required: coulomb.Quantity[Long, (1 : Int)]

where:    ?1 is an unknown value of type coulomb.ops.standard.tquot.infra.TQuotNC[Long, coulomb.units.time.Hour, Long, 
  coulomb.units.si.Second
, Long, coulomb.units.time.Hour / coulomb.units.si.Second]

  def intervalsPerDay: Quantity[Long, 1] = 24L.withUnit[Hour].tquot(interval)
```

If I uncomment the unsimplified unit `coulomb.units.time.Hour / coulomb.units.si.Second` it compiles, but of course I'd like hours and seconds to cancel out to dimensionless.

Could there be an issue with simplification of time unit types?

2.

Separately, Ive been experimenting with _exporting_ all the required Coulomb definitions. I have a file `Basetypes.scala` that builds on top of Coulomb, and all my other files import is like so `import basetypes.{*, given}`.

Within `Basetypes.scala` I export Coulomb to try to centralize all the imports and not duplicates them across 10s of files. It seems to be working, but note I had to hide the re-export of `Second` from `si` into `time` to avoid a double-definition error.

```
package basetypes

export coulomb.{Quantity, DeltaQuantity, `*`, `/`, `^`, showUnit}
export coulomb.syntax.{withUnit, withDeltaUnit}
export allalgebra.given
export coulomb.ops.algebra.all.given
export coulomb.policy.standard.given
export coulomb.units.time.{*, given}
export coulomb.units.si.{Second as _, ctx_unit_Second as _, *, given}
export coulomb.units.si.prefixes.{*, given}

private object allalgebra extends algebra.instances.AllInstances
```

To be clear this certainly isn't a _bug_, but it is a potential issue that users of Coulomb may encounter. This need to hide re-exported members seems a small issue now, but it grows larger & problematic the more exporting is utilized. 

It begs the question, is `export` (which creates duplicate members in the exporting namespace) something intended to be used only within the Coulomb library, or also by application users of Coulomb?

Given this [discussion on Scala contributors about how we're supposed to achieve DRY imports in Scala 3](https://contributors.scala-lang.org/t/idiomatic-imports/5788), export was proposed as the blessed technique. 

So personally, I will try to design app codebases where library imports are exported in central definitions like `basetypes`. But this seems likely to conflict with library authors like yourself @erikerlandson who may also wish to do the same thing (eg between `si` and `time` packages).

**Comment by erikerlandson** [comment]
You are correct, I currently do not simplify that sort of expression.  As a workaround you can always append `.toUnit[1]`

The reason I do not simplify various expressions that might be simplified was that

- it's pretty easy to append `.toUnit[MyDesiredUnitExpr]` if the exact form matters
- if "standard" policy is enabled, convertable expressions will automatically convert (implicit conversions)
- I was hesitant to get sucked into making decisions about what a "correct simplification" is, or should be, since that is likely to be a matter of user requirements or aesthetics.
- the result of the conversion technically must make its way into the Value, and that can cause numeric effects and may require extra machinery

However - I have also seen that kind of thing and been annoyed by it, so I could take another look at handling that particular case of unitless results.

**Comment by erikerlandson** [comment]
Regarding 2 (exporting) there is a constraint there: currently you can ONLY export from an `object:` block, and you cannot export from a `package`.

So there are some things which are not defined under `object` - these are cases where the I wanted the scoping to be inside `package` scope which can be defined across multiple source files.  `object` can of course only be defined once, in one file.

I do not know if scala-3 has any plans to support `export` from a `package`.  I hope so.  Possibly @armanbilge  knows what the plan for that is.

Anyway for better or worse, you won't be able to `export` various coulomb definitions that are not defined under an `object` - you will have to `import` them explicitly wherever you need them.

**Comment by armanbilge** [comment]
> currently you can ONLY export from an `object:` block, and you cannot export from a `package`.

Sorry, can you clarify this point? I've definitely `export`ed from a package before:

https://github.com/armanbilge/calico/blob/618c64a3e0aa0d2ed9c62e881907a85ec79e0d18/calico/src/main/scala/calico/unsafe/MacrotaskExecutor.scala#L19

There, it is exporting `MacrotaskExecutor` which is defined in the `org.scalajs.macrotaskexecutor` package into the `calico.unsafe` package.

**Comment by erikerlandson** [comment]
@armanbilge   I made a concerted attempt a while back to get that to work, and failed completely. So, once again scala baffles me :sob:

**Comment by erikerlandson** [comment]
I specifically wanted to include some package definitions in my policy exports (like `coulomb.Quantity`, etc), and it wasn't working for me.

**Comment by benhutchison** [comment]
IIUC package exports are unable to use * and must explicitly list all
exported members. Maybe that's what bit you @erikerlandson?

**Comment by benhutchison** [comment]
I accept the workarounds are not arduous, however automatic simplification
for the unitless case seems like it would be a convenient feature.

**Comment by benhutchison** [comment]
Erik, actually when I try the suggested `toUnit` workaround I git a compile error:
```
[error] 34 |  def intervalsPerDay: Quantity[Long, 1] = 24L.withUnit[Hour].tquot(interval).toUnit[1]
[error]    |                                                                                       ^
[error]    |No unit conversion in scope for value type Long, unit types coulomb.units.time.Hour / coulomb.units.si.Second => (1 : Int)
```

Do you know why this might be?

PS these are my imports:
TimeUnit.scala
```
import basetypes.{*, given}
```
Basetypes.scala
```
package basetypes

import scala.annotation.targetName

export coulomb.{Quantity, DeltaQuantity, `*`, `/`, `^`, showUnit}
export coulomb.syntax.{withUnit, withDeltaUnit}
export allalgebra.given
export coulomb.ops.algebra.all.given
export coulomb.policy.standard.given
export scala.language.implicitConversions
export coulomb.units.time.{*, given}
export coulomb.units.si.{Second as _, ctx_unit_Second as _, *, given}
export coulomb.units.si.prefixes.{*, given}

private object allalgebra extends algebra.instances.AllInstances
```

**Comment by erikerlandson** [comment]
@benhutchison  that is because your value types are integers. `.tToUnit[1]` should work

**Comment by benhutchison** [comment]
Thanks Erik, that does resolve it.. I'm still internalizing the truncation
family of ops for integers.
