### ISSUE TITLE
toInstant doesnt compile for millisecond Long timestamp

### ISSUE THREAD

**Issue by benhutchison** [erikerlandson/coulomb#419]
Single line change in this branch: https://github.com/benhutchison/coulomb/tree/toInstant

```
    test("toInstant") {
        import coulomb.units.javatime.conversions.explicit.given

        val et = (-165L).withEpochTime[Day]
        (-165L).withEpochTime[Milli * Second].toInstant  //wont compile  
        assertEquals(et.toInstant.toString, "1969-07-20T00:00:00Z")
    }
```

**Comment by benhutchison** [comment]
Hi @erikerlandson I think I need your help to resolve this. The blowup that causes this compile error is an unhandled case within the metaprogramming layer of coulomb.

While I'm somewhat familiar with the user-facing apis and implicit typeclasses of Coulomb, I don't know Scala 3 metaprogramming. In truth, my trial of adopting coulomb is dependent on your willingness to support the library, at least the interior layers.

**Comment by erikerlandson** [comment]
@benhutchison  good find, the `offset` code in the metaprogramming was wrong: v0.7.3 should fix it

**Comment by benhutchison** [comment]
Thanks Erik 🙏 🎉
