### ISSUE TITLE
timestamp as an analog to temperature

### ISSUE THREAD

**Issue by erikerlandson** [erikerlandson/coulomb#51]
For temperature and quantities of degrees, we have:
```
Temp +/- Quantity => Temp
Temp - Temp => Quantity
```
A very similar relationship applies to Quantity of time units and date-time stamps.

**Comment by erikerlandson** [comment]
There is a generalizable concept here.  A unit is inherently "zero-based" - it has no offset per se. But you can turn it into a "unit with offset".  Currently `Temperature` is a particular example of this: a "quantity of thermal degrees, with an offset".  Time units also have this.  A time unit, with offset from 1970, is a Date.

In theory, any unit can be turned into one of these "unit with offset" objects.  A unit of length can be turned into a "location" by adding some kind of offset, for example.

In that respect, both `Temperature` and `Date` could be named type aliases for this `UnitWithOffset` object, but I'm grappling with what the best abstraction is.  Currently `Temperature` is treated as a special case.  Naming is also a question.  `UnitWithOffset` doesn't exactly roll off the tongue. Is there a preferable name?

**Comment by elmiko** [comment]
this does not sound insane to me. i think it would be neat to have some sort of mixin for offsetable types, but i'm not sure it fits the programming model or best practice here.

**Comment by erikerlandson** [comment]
```scala
type CelsiusTemp
implicit val defineCelsiusTemp = LocalizedUnit[CelsiusTemp, Celsius](273.15)
```

I think I might not even need a special type `Temperature`, with my plans for factoring numeric operations out into implicit class.  The "normal" vector-like units (Celsius) will successfully instantiate the allowable numeric operations on such units.  Localized, "point-like" units such as CelsiusTemp will be able to instantiate the operations pertaining to them.

Dates and times are still subtly tricky here.  I can easily enough define something like
```scala
type UnixEpochSecond
implicit val defineUnixEpochSecond = LocalizedUnit[UnixEpochSecond, Second](0)
```
This is not quite as clean as for temps. With temperature, there is a well-defined universal zero (0K), but for time there isn't really such a number.  The best analog would be "the beginning of time", for which we don't have any precise value. The above isn't meaningless, but if I wanted to define something like:
```scala
type GregorianSeconds
implicit val defineGregorianSeconds = LocalizedUnit[GregorianSeconds, Second](xxx) 
```
What is the correct value for `xxx` ?  I could define it relative to `UnitEpochSecond`, but that is not as rock-solid a reference as "the physical value for absolute zero".

Possibly still useful, but I'll have to think on it.

**Comment by erikerlandson** [comment]
I don't like the name `LocalizedUnit`.  `PositionalUnit` ?
`RelativeUnit` ?
`OffsetUnit` ?

**Comment by erikerlandson** [comment]
```scala
trait Kelvin
implicit val defineUnitKelvin = BaseUnit[Kelvin](name = "Kelvin", abbv = "K")

trait Celsius
implicit val celsius = DerivedUnit[Celsius, Kelvin](1, "Celsius", "C")

implicit val kelvinTemp = BaseUnitOffset[Kelvin](offset = 0)

implicit val celsiusTemp = DerivedUnitOffset[Celsius, Kelvin](offset = 273.15)

trait Second
implicit val defineUnitSecond = BaseUnit[Second]()

implicit val unixEpochSeconds = BaseUnitOffset[Second](offset = 0)

// this system assumes unique BaseUnitOffset for any type
trait OffsetQuantity[N, U, B] { ... }

type Temperature[N, U] = OffsetQuantity[N, U, BaseUnitOffset[Kelvin]]

type UnixTime[N, U] = OffsetQuantity[N, U, BaseUnitOffset[Second]]
```

**Comment by erikerlandson** [comment]
I have refactored `Temperature` to be a special case of `OffsetQuantity` on #66. I think I'm now in a good position to define something similar for `EpochTime`

**Comment by erikerlandson** [comment]
added on #66
