### ISSUE TITLE
Make implicit hints possible

### ISSUE THREAD

**Issue by mhriemers** [erikerlandson/coulomb#56]
Currently, one is unable to provide a `MulResultType` because it is package private. IntelliJ has a lot of problems resolving the implicits so type inference is very poor. This could be improved by providing some of these instances explicitly.

**Comment by erikerlandson** [comment]
I tried to make things private when I thought they were not candidates for customization, just to minimize the load on the compiler (which coulomb works pretty hard in the best case).  I have no experience with IDEs, so I don't have much feel for what problems you are seeing w/ IntelliJ. I know that even the Scala compiler was having trouble resolving the coulomb implicit chains until 2.13, so I can imagine IJ struggling with it.

**Comment by mhriemers** [comment]
I'm not familiar with the performance gains of putting certain things in package private. Is it substantial? I agree with you that for people not using an IDEA it is unnecessary to include these explicit types. Maybe we could make it an extra package people could optionally include.

**Comment by erikerlandson** [comment]
Removing `private [coulomb]` didn't seem to make compilation slower. If anything it was faster.
I'm resolving this on #66
