### ISSUE TITLE
cross-compile for scala.js

### ISSUE THREAD

**Issue by erikerlandson** [erikerlandson/coulomb#79]
I know absolutely nothing about scala.js or its ecosystem.

If I'm lucky, sbt-crossproject would allow me to fake this.
https://github.com/portable-scala/sbt-crossproject

**Comment by cquiroz** [comment]
I could try to do this, I've done a bunch of scala.js projects and we may need coulomb

**Comment by erikerlandson** [comment]
@cquiroz if you want to take a stab at it, please feel free!  I'm hoping it's mostly additional targets in sbt, and corresponding in travis ci

**Comment by cquiroz** [comment]
It is blocked on spire that hasn't been released yet for scala.js 1.0

**Comment by erikerlandson** [comment]
crossref: https://github.com/typelevel/spire/pull/888

**Comment by erikerlandson** [comment]
Looks like the "real" problem is the archival of machinist
https://github.com/typelevel/spire/pull/888#issuecomment-616420331

**Comment by erikerlandson** [comment]
@cquiroz I believe spire 0.17.0-RC1 is building with scalaJS 1.x

**Comment by cquiroz** [comment]
Yes, I'm waiting for a release

**Comment by erikerlandson** [comment]
https://github.com/typelevel/spire/releases/tag/v0.17.0-RC1

**Comment by erikerlandson** [comment]
scala-steward updated to spire 0.17.0-RC1, which I merged, so if you rebase from `develop` ScalaJS 1.x should in theory work now

**Comment by cquiroz** [comment]
Yes I'm updating the build, will send a PR soon

**Comment by cquiroz** [comment]
Actually I found a show stopper. coulomb uses `WeakTypeTags` which aren't available on scala.js. I'm not very familiar with them, I dont know if coulomb could use something else

**Comment by erikerlandson** [comment]
I can try `ClassTag`
https://github.com/scala-js/scala-js/issues/50#issuecomment-32093548

Mostly I'm using them to provide default names based on the name of a type.

Another possible approach would be to not support defaults that require WeakTypeTag or TypeTag, or not support them in scala.js - the code would need some refactoring to support that kind of dual functionality.

Or possibly punt to macros. those are supported IIUC

Maybe a dedicated implicit `GetTypeName`, that could punt to a macro or just invoke WeakTypeTag.  I was excited about getting rid of the scala-2.x macros and I'm not eager to bring them back, but maybe if they were only invoked for scala.js ... ?

Scala's support for "conditional compilation" is pretty awkward, but I see people do it.

If we are ultimately forced to use macros, this is nice and compact.
https://stackoverflow.com/a/15649874/3669757

**Comment by cquiroz** [comment]
@tpolecat sugested to use shapeless `Typeable` to get the names. Some uses are in libs that are jvm only like pureconfig thus we wouldn't need to change them

**Comment by cquiroz** [comment]
I can try todo it and make sure they'd run in scala.js

**Comment by erikerlandson** [comment]
> @tpolecat sugested to use shapeless Typeable to get the names. 

Sounds like a good approach, shapeless is already a dependency.  If it works, I'm happy to use it everywhere.  I recently migrated everything to `WeakTypeTag` for consistency.

It might be worth using a shim `GetTypeName` in case this needs to be changed yet again in the future.  GetTypeName could call Typeable for now.

**Comment by erikerlandson** [comment]
closing with #97 
QuantityParser and its deps are not supported in scalaJS in their current form, that will require a future redesign
